import assert from 'node:assert/strict';
import {estimateCost,experimentInput,stableInput} from '../lib/cost.ts';
import {calculate,DEFAULT_CONFIG,DEFAULT_QUERY,DEFAULT_DOCUMENT,DEFAULT_SYSTEM} from '../lib/rag-engine.ts';
const s={temperature:0,maxTokens:512};
const a=calculate(DEFAULT_QUERY,DEFAULT_DOCUMENT,DEFAULT_SYSTEM,DEFAULT_CONFIG);
const b=calculate(DEFAULT_QUERY,DEFAULT_DOCUMENT,DEFAULT_SYSTEM,{...DEFAULT_CONFIG,topK:1});
assert.equal(estimateCost(a,s).changeCostUsd,0);
assert.ok(estimateCost(a,s).inputTokens>estimateCost(b,s).inputTokens);
assert.ok(estimateCost(a,{...s,maxTokens:1024}).totalUsd>estimateCost(a,s).totalUsd);
assert.equal(estimateCost(a,{...s,temperature:.8}).totalUsd,estimateCost(a,s).totalUsd);
const input=experimentInput(a,s);
assert.equal(stableInput(input),stableInput({...input,config:{budget:650,rerank:true,topK:3,overlap:30,size:180}}));
for(const other of [{...input,query:'different'},{...input,document:'different'},{...input,system:'different'},{...input,settings:{...s,temperature:.5}},{...input,config:{...input.config,overlap:40}}])assert.notEqual(stableInput(input),stableInput(other));
assert.ok(!JSON.stringify(input).includes('apiKey'));
console.log('PASS: offline estimates, output budgets, canonical identity and cache invalidation dimensions. No provider calls.');
