"use client";
import {useState,useEffect,useRef} from "react";
import {Play,Pause,RotateCcw,Pin,ArrowUpRight,FileText,Search} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Switch} from "@/components/ui/switch";
import {HoverCard,HoverCardContent,HoverCardTrigger} from "@/components/ui/hover-card";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {useLab} from "@/components/workspace";
import {Control,steps,StageDetails,stageValue} from "@/components/lab-details";
import {estimateCost} from "@/lib/cost";
import {DEFAULT_CONFIG,type Config} from "@/lib/rag-engine";
const coords=[[80,95],[325,95],[570,95],[815,95],[815,330],[570,330],[325,330],[80,330]];
const edges=["M260 155H325","M505 155H570","M750 155H815","M905 215V330","M815 390H750","M570 390H505","M325 390H260"];
export default function Page(){
 const {input,result,update,pin}=useLab();const [stage,setStage]=useState<number|null>(null),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(-1),[zoom,setZoom]=useState(.75),[playbackPopup,setPlaybackPopup]=useState(false),[inference,setInference]=useState<{state:"idle"|"running"|"done"|"error";text:string}>({state:"idle",text:""});const canvas=useRef<HTMLDivElement>(null),inferenceStarted=useRef(false);
 useEffect(()=>{const el=canvas.current;if(!el)return;const resize=new ResizeObserver(()=>setZoom(Math.min(1,Math.max(.5,(el.clientWidth-20)/1075))));resize.observe(el);return()=>resize.disconnect();},[]);
 useEffect(()=>{setPlaying(false);setProgress(-1);setPlaybackPopup(false);inferenceStarted.current=false;setInference({state:"idle",text:""})},[input]);
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{if(progress>=7)setPlaying(false);else setProgress(v=>v+1)},850);return()=>clearTimeout(timer)},[playing,progress]);
 useEffect(()=>{if(progress!==7)return;setPlaybackPopup(true);const timer=setTimeout(()=>setPlaybackPopup(false),3000);return()=>clearTimeout(timer)},[progress]);
 useEffect(()=>{if(!playing||progress!==7||inferenceStarted.current)return;inferenceStarted.current=true;setPlaying(false);setInference({state:"running",text:"근거 추출 결과에 도착했습니다. 현재 RAG context로 Gemini 추론 중…"});void (async()=>{try{const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input),signal:AbortSignal.timeout(55000)});const data=await response.json() as {text?:string;error?:string};if(!response.ok)throw Error(data.error||"LLM 추론에 실패했습니다.");setInference({state:"done",text:data.text||"모델이 텍스트를 반환하지 않았습니다."});}catch(error){setInference({state:"error",text:error instanceof Error?error.message:"LLM 추론에 실패했습니다."})}})()},[input,playing,progress]);
 function config(p:Partial<Config>){const next={...input.config,...p};next.overlap=Math.min(next.overlap,next.size-1);update({config:next});}
 function startPlayback(){setInference({state:"idle",text:""});inferenceStarted.current=false;setPlaybackPopup(false);setProgress(0);setPlaying(true);}
 function peek(i:number){if(i===0)return input.document.slice(0,170);if(i===1)return result.chunks.slice(0,2).map(c=>`${c.id} [${c.start}–${c.end}] ${c.text.slice(0,95)}`).join("\n\n");if(i===2)return `[${result.queryVector.filter(v=>v>0).slice(0,5).map(v=>v.toFixed(3)).join(", ")}…]`;if(i===3||i===4)return result.candidates.map(c=>`${c.id} · ${c.score.toFixed(3)}`).join("\n");if(i===5)return result.context.slice(0,200);if(i===6)return result.prompt.slice(0,200);if(i===7&&inference.state==="done")return `[B · Gemini 실제 추론]\n${inference.text}`;if(i===7)return result.evidence.length?result.evidence.map(e=>`${e.text} [${e.id}]`).join("\n\n"):result.answer;return result.answer.slice(0,200);}
 function playbackPeek(i:number){if(i===7&&inference.state!=="idle")return `${peek(i)}\n\n[ B · Gemini 실제 추론 ]\n${inference.text}`;return peek(i);}
 const cost=estimateCost(result,input.settings);
 return <><div className="page-title"><div><p>BUILD AN UNDERSTANDING</p><h1>질문 하나로, RAG의 모든 단계를.</h1><span>노드에 마우스를 올려 미리 보고, 클릭해서 깊이 살펴보세요.</span></div><a href="/compare" className="primary-link">A/B 비교 열기 <ArrowUpRight size={16}/></a></div>
 <div className="studio-question"><Search size={19}/><Input aria-label="질문" maxLength={300} value={input.query} onChange={e=>update({query:e.target.value})}/><Button variant="outline" onClick={()=>setStage(0)}><FileText size={15}/>원문 편집</Button></div>
 <div className="pipeline-workspace"><aside className="compact-controls"><div className="control-heading"><b>실험 설정</b><span>B · LIVE</span></div><Control label="Chunk size" value={input.config.size} min={60} max={400} step={10} onChange={size=>config({size})} unit="자" note="검색할 조각의 크기"/><Control label="Overlap" value={input.config.overlap} min={0} max={input.config.size-1} onChange={overlap=>config({overlap})} unit="자" note="청크 사이에 겹치는 문맥"/><Control label="Top-K" value={input.config.topK} min={1} max={8} onChange={topK=>config({topK})} note="검색 후보 수"/><Control label="Context budget" value={input.config.budget} min={200} max={1600} step={50} onChange={budget=>config({budget})} unit="자" note="모델에 전달할 근거 예산"/><div className="compact-switch"><label htmlFor="rerank-studio">후보 재정렬</label><Switch id="rerank-studio" checked={input.config.rerank} onCheckedChange={rerank=>config({rerank})}/></div><Button onClick={pin}><Pin size={15}/>현재 설정을 A로 고정</Button><Button variant="ghost" onClick={()=>update({config:DEFAULT_CONFIG})}><RotateCcw size={14}/>설정 초기화</Button></aside>
 <section className="canvas-panel"><div className="canvas-toolbar"><div><span className="live-dot"/><b>RAG Pipeline</b><small>{playing?`${progress+1} / 8 단계 재생`:progress===7?"재생 완료":"실시간 계산"}</small></div><div><Button size="sm" variant="outline" aria-label="축소" onClick={()=>setZoom(v=>Math.max(.65,v-.1))}>−</Button><Button size="sm" variant="ghost" onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</Button><Button size="sm" variant="outline" aria-label="확대" onClick={()=>setZoom(v=>Math.min(1.4,v+.1))}>+</Button><Button size="sm" onClick={()=>{if(playing)setPlaying(false);else startPlayback()}}>{playing?<Pause size={14}/>:<Play size={14}/>} {playing?"일시정지":"흐름 재생"}</Button></div></div>
 <div className="graph-scroll" ref={canvas}><div className="graph-space" style={{width:1075*zoom,height:550*zoom}}><div className="graph-content" style={{transform:`scale(${zoom})`}}><span className="graph-lane lane-one">01 / INDEXING · 문서를 검색 가능한 형태로</span><span className="graph-lane lane-two">02 / RETRIEVAL & CONTEXT · 질문에 필요한 근거로</span><svg className="graph-edges" viewBox="0 0 1075 550" aria-label="문서, 청킹, 벡터 변환, 검색, 재정렬, 컨텍스트, 프롬프트, 근거 추출 순서"><defs><marker id="edge-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#90a3bc"/></marker></defs>{edges.map((d,i)=><g key={d}><path d={d} className={progress>i?"graph-edge processed":"graph-edge"} markerEnd="url(#edge-arrow)"/>{playing&&progress===i&&<circle r="4" fill="#5378ee"><animateMotion dur=".85s" repeatCount="indefinite" path={d}/></circle>}</g>)}</svg>
 {steps.map((s,i)=>{const Icon=s.icon;const active=playing&&progress===i||progress===7&&i===7&&playbackPopup;return <div key={s.en} className="graph-node-position" style={{left:coords[i][0],top:coords[i][1]}}><HoverCard openDelay={150} closeDelay={180}><HoverCardTrigger asChild><button className={`graph-node ${progress===i?"node-running":""}`} onClick={()=>setStage(i)} aria-label={`${i+1}. ${s.name} 상세 보기`}><span className={`node-icon tone-${i%4}`}><Icon size={21}/></span><span className="node-number">0{i+1}</span><strong>{s.name}</strong><small>{stageValue(result,i)}</small><i className="port input"/><i className="port output"/></button></HoverCardTrigger><HoverCardContent className="node-preview" side="top"><b>{s.name} · 현재 데이터</b><p>{peek(i)||"입력을 추가하세요."}</p><small>클릭하면 전체 데이터와 동작 원리를 볼 수 있어요.</small></HoverCardContent></HoverCard>{active&&<div className="node-preview playback-preview" role="status"><b>{s.name} · 재생 결과</b><p>{playbackPeek(i)||"계산 중…"}</p><small>{i===7?"B 입력으로 Gemini 추론까지 완료합니다.":"현재 RAG 계산 결과입니다."}</small></div>}</div>})}</div></div></div>
 <div className="canvas-summary"><span><b>{result.chunks.length}</b> 청크</span><span><b>{result.selected.length}</b> 선택된 근거</span><span>입력 <b>약 {cost.inputTokens}</b> 토큰</span><span>생성 예산 <b>${cost.totalUsd.toFixed(6)}</b></span><span className="free-tag">설정 변경 $0</span></div><p className="cost-note">현재 RAG prompt {cost.promptChars}자 · context {cost.contextChars}자 · 출력 최대 {input.settings.maxTokens}토큰 기준. Chunk/Overlap이 선택 context를 바꾸지 않으면 예상 비용이 같을 수 있습니다.</p></section></div><section className={`playback-inference playback-${inference.state}`} aria-live="polite"><b>{inference.state==="idle"?"흐름 재생 후 LLM 추론":"흐름 재생 LLM 추론"}</b><p>{inference.state==="idle"?"흐름 재생이 근거 추출 결과에 도착하면 현재 질문·선택 chunk·RAG context를 사용해 실제 모델을 한 번 호출합니다.":inference.text}</p></section><p className="studio-footnote">검색: 학습용 TF-IDF · 비용: 문자 기반 추정 · 애니메이션은 처리 순서 설명용입니다. 흐름 재생 완료 시 실제 생성 답변을 호출합니다.</p>
 <Sheet open={stage!==null} onOpenChange={open=>{if(!open)setStage(null)}}><SheetContent className="inspector-sheet"><SheetHeader><SheetTitle>{stage!==null?steps[stage].name:"단계 상세"}</SheetTitle><SheetDescription>{stage!==null?steps[stage].description:""}</SheetDescription></SheetHeader>{stage!==null&&<div className="inspector-body"><StageDetails stage={stage} r={result} selected={new Set(result.selected.map(c=>c.id))} chosen={null} onChoose={()=>{}} onDocument={document=>update({document})} onSystem={system=>update({system})} onCite={()=>setStage(1)} llmText={stage===7&&inference.state==="done"?inference.text:undefined}/><p className="inspector-note">{steps[stage].pitfall}</p></div>}</SheetContent></Sheet></>;
}
