"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowDown, ArrowRight, BookOpen, Check, ChevronRight, Code2, Database, FileText, Fingerprint, GitCompareArrows, Layers3, Pause, Pin, Play, RotateCcw, Search, Settings2, SkipForward, Sparkles, Split, Terminal, Waypoints } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { calculate, DEFAULT_CONFIG, DEFAULT_DOCUMENT, DEFAULT_QUERY, DEFAULT_SYSTEM, type Config, type Result } from "@/lib/rag-engine";

export const steps = [
  {name:"원본 문서",en:"DOCUMENT",icon:FileText,description:"원문과 질문이 모든 단계의 공통 입력입니다. 실제 시스템에서는 PDF·HTML 등을 추출하고 출처·페이지·적용일 메타데이터를 보존합니다.",formula:"document → text + source",pitfall:"가상 출장 규정으로 실험합니다. 회사의 실제 규정이 아닙니다."},
  {name:"청크 분할",en:"CHUNKING",icon:Split,description:"원문을 고정 문자 길이로 나눕니다. 다음 시작 위치는 이전 시작 위치 + size − overlap입니다. 노란 부분이 앞 청크와 겹친 문맥입니다.",formula:"next_start = start + size − overlap",pitfall:"이 실험은 경계 효과를 보여주기 위한 문자 단위 청킹입니다. 실제 서비스에서는 토큰·문단·표 구조를 고려하세요."},
  {name:"벡터 변환",en:"VECTORIZATION",icon:Fingerprint,description:"각 단어에서 연속된 두 글자를 뽑아 TF-IDF 가중치를 계산하고 길이 1로 정규화합니다. 질문도 같은 사전과 가중치로 변환합니다.",formula:"w = (1 + ln TF) × IDF / norm",pitfall:"실제로 계산하는 어휘 기반 벡터입니다. 신경망 임베딩이 아니므로 동의어·의미 추론은 지원하지 않습니다."},
  {name:"Top-K 검색",en:"RETRIEVAL",icon:Search,description:"질문 벡터와 모든 청크 벡터의 코사인 유사도를 계산합니다. 점수가 0보다 큰 청크 중 상위 K개를 후보로 선택합니다.",formula:"score = Σ query[i] × chunk[i]",pitfall:"점수는 정답 확률이 아닙니다. Top-K를 늘리면 후보뿐 아니라 잡음도 늘어날 수 있습니다."},
  {name:"후보 재정렬",en:"RERANKING",icon:Layers3,description:"검색된 후보 안에서 질문의 두 글자 특징이 얼마나 포함되는지 다시 비교합니다. ON/OFF에 따라 순서와 예산에 들어가는 청크가 달라질 수 있습니다.",formula:"score = 0.65 × feature coverage + 0.35 × cosine",pitfall:"학습용 휴리스틱입니다. 실제 cross-encoder가 아니며 첫 검색에서 빠진 후보를 되살리지 못합니다."},
  {name:"근거 묶음",en:"CONTEXT",icon:Database,description:"순서대로 청크를 확인해 문자 예산에 들어가는 것만 담습니다. 남은 예산보다 큰 청크는 건너뜁니다. 출처 ID를 붙여 다음 단계에 전달합니다.",formula:"selected chunks + source IDs → context",pitfall:"Top-K는 검색 후보 수, 여기에 표시되는 수는 실제 사용한 근거 수입니다. 둘은 다를 수 있습니다."},
  {name:"최종 프롬프트",en:"PROMPT",icon:Terminal,description:"시스템 지시문 + 선택된 문맥 + 처음 입력한 질문을 합칩니다. 이 텍스트가 실제 LLM에 전송할 입력에 해당합니다.",formula:"SYSTEM + CONTEXT + QUESTION",pitfall:"시스템 지시문은 조립된 프롬프트에 반영됩니다. 위의 추출 알고리즘은 지시문을 해석하지 않습니다. 아래 실제 LLM 생성에서는 이 지시문을 모델에 전달합니다."},
   {name:"근거 추출 결과",en:"ANSWER",icon:Sparkles,description:"추론 전에는 선택된 청크 안의 원문 문장을 로컬에서 추출합니다. 흐름 재생이 이 단계에 도착하면 현재 B의 질문·RAG context를 Gemini에 보내 실제 답변으로 바꿔 확인합니다.",formula:"local evidence → RAG context → Gemini answer",pitfall:"로컬 근거 문장과 Gemini 답변은 서로 다른 결과입니다. 근거가 부족하면 모델이 추측하지 않도록 시스템 지시문을 확인하고, 실제 답변에는 선택된 chunk만 사용됩니다."},
];
export const stageValue = (r:Result,i:number) => [`${r.chars.toLocaleString()}자`,`${r.chunks.length} chunks`,`${r.vocabulary.length}차원`,`${r.candidates.length} candidates`,r.config.rerank?"ON · 재정렬":"OFF · 원순위",`${r.selected.length} chunks`,`${r.prompt.length}자`,`${r.evidence.length}개 근거 문장`][i];
const COLORS=["#b9f570","#72ddd4","#9dacf8","#efbd68","#da99de","#70c8f5"];
const fmt=(v:number)=>v.toFixed(3);

export function Control({label,value,min,max,step=1,onChange,note,unit=""}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void;note:string;unit?:string}) {
 const sliderHost=useRef<HTMLDivElement>(null);
 useEffect(()=>{const frame=requestAnimationFrame(()=>sliderHost.current?.querySelector("[role=slider]")?.setAttribute("aria-label",label));return()=>cancelAnimationFrame(frame)},[label]);
 return <div className="parameter" ref={sliderHost}><div><label>{label}</label><output>{value}<small>{unit}</small></output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])}/><p>{note}</p></div>;
}
export function NodeArt({index,r}:{index:number;r:Result}){
 if(index===0)return <div className="node-art text-lines">{[90,72,96,56].map((w,i)=><i key={i} style={{width:w+"%"}}/>)}</div>;
 if(index===1)return <div className="node-art mini-chunks">{r.chunks.slice(0,8).map((c,i)=><i key={c.id} style={{background:COLORS[i%6]}}/>)}</div>;
 if(index===2)return <div className="node-art vector-cells">{r.queryVector.filter(v=>v>0).slice(0,24).map((v,i)=><i key={i} style={{opacity:Number((.25+Math.min(v*3,.75)).toFixed(3))}}/>)}</div>;
 if(index===3||index===4)return <div className="node-art mini-bars">{(index===3?r.candidates:(r.config.rerank?[...r.candidates].sort((a,b)=>b.rerankScore-a.rerankScore):r.candidates)).slice(0,4).map(c=><i key={c.id} style={{width:Math.max(10,(index===3?c.score:c.rerankScore)*150)+"%"}}/>)}</div>;
 if(index===5)return <div className="node-art context-strips">{r.selected.slice(0,4).map(c=><i key={c.id}>{c.id}</i>)}</div>;
 if(index===6)return <div className="node-art mini-code"><i>SYS <span/></i><i>CTX <span/></i><i>USR <span/></i></div>;
 return <div className="node-art mini-answer"><Sparkles size={20}/><span>{r.evidence.length} sentences</span></div>;
}
function Stat({label,value,suffix,delta}:{label:string;value:number;suffix:string;delta:number}){return <div><span>{label}</span><strong>{value.toLocaleString()}<small>{suffix}</small></strong><em>{delta===0?"A와 동일":`A 대비 ${delta>0?"+":""}${delta.toLocaleString()}`}</em></div>}
export function StageDetails({stage,r,selected,chosen,onChoose,onDocument,onSystem,onCite,llmText}:{stage:number;r:Result;selected:Set<string>;chosen:string|null;onChoose:(s:string)=>void;onDocument:(s:string)=>void;onSystem:(s:string)=>void;onCite:(s:string)=>void;llmText?:string}){
 if(stage===0)return <><label className="input-label" htmlFor="document-input">공통 원문 · 직접 수정해서 모든 결과에 반영</label><Textarea id="document-input" value={r.document} maxLength={6000} onChange={e=>onDocument(e.target.value)} className="document-input"/><div className="query-footer"><span>문자 오프셋은 0부터 시작합니다.</span><span>{r.chars}/6,000자</span></div></>;
 if(stage===1)return <><div className="chunk-map" aria-label="원문 위 청크 범위">{r.chunks.map((c,i)=><button aria-label={`${c.id} 원문 범위 ${c.start}부터 ${c.end}`} key={c.id} onClick={()=>onChoose(c.id)} style={{marginLeft:(c.start/Math.max(1,r.chars))*100+"%",width:((c.end-c.start)/Math.max(1,r.chars))*100+"%",background:COLORS[i%6]}} title={`${c.start}–${c.end}`}>{c.id}</button>)}</div><div className="legend"><span><i/>앞 청크와 겹치는 문맥</span><span>✓ 최종 컨텍스트에 포함</span></div><div className="chunk-inspector">{r.chunks.length?r.chunks.map((c,i)=><article key={c.id} className={`data-chunk ${chosen===c.id?"chosen":""}`} style={{borderLeftColor:COLORS[i%6]}}><header><b>{c.id}</b><span>{c.start}–{c.end} · {c.text.length}자</span>{selected.has(c.id)&&<Check size={16}/>}</header><p><mark>{c.text.slice(0,c.overlap)}</mark>{c.text.slice(c.overlap)}</p></article>):<p>원문을 입력하면 청크가 생성됩니다.</p>}</div></>;
 if(stage===2){const dimensions=r.vocabulary.map((term,i)=>({term,i,weight:r.queryVector[i]})).filter(t=>t.weight>0).slice(0,16);return <><div className="vector-caption"><b>{r.vocabulary.length}차원 · 실제 계산된 TF-IDF 벡터</b><span>질문 값이 있는 앞 16개 차원만 표시</span></div><div className="matrix"><Table><TableHeader><TableRow><TableHead>두 글자 특징</TableHead><TableHead>질문</TableHead>{r.chunks.slice(0,3).map(c=><TableHead key={c.id}>{c.id}</TableHead>)}</TableRow></TableHeader><TableBody>{dimensions.map(d=><TableRow key={d.term}><TableCell>{d.term}</TableCell><TableCell><Heat v={d.weight}/></TableCell>{r.chunks.slice(0,3).map(c=><TableCell key={c.id}><Heat v={c.vector[d.i]}/></TableCell>)}</TableRow>)}</TableBody></Table></div><div className="vector-caption"><span>사전은 청킹 결과에서 다시 만듭니다. 청크 변경 → IDF 변경 → 순위 변경이 가능합니다.</span></div></>}
 if(stage===3||stage===4){const rows=stage===3?r.ranked:(r.config.rerank?[...r.candidates].sort((a,b)=>b.rerankScore-a.rerankScore||a.rank-b.rank):r.candidates);return <RankList rows={rows} r={r} rerank={stage===4}/>;}
 if(stage===5)return <><div className="budget-label"><b>{r.used} / {r.config.budget}자 사용</b><span>{r.candidates.length}개 후보 → {r.selected.length}개 채택</span></div><div className="budget-bar">{r.selected.map((c,i)=><div key={c.id} style={{width:((c.text.length+c.id.length+5)/r.config.budget)*100+"%",background:COLORS[i%6]}}>{c.id}</div>)}</div><p className="muted">예산 계산은 청크 본문과 출처 구분용 여유 문자를 포함합니다. 문장 일부를 잘라 채우지 않습니다.</p><pre className="data-code">{r.context||"선택된 근거 없음"}</pre>{r.candidates.length>r.selected.length&&<p className="compare-warning">예산 때문에 {r.candidates.length-r.selected.length}개 후보가 제외됐습니다. Top-K를 늘려도 예산이 같으면 결과가 그대로일 수 있습니다.</p>}</>;
 if(stage===6)return <><label htmlFor="system-input" className="input-label">SYSTEM 지시문 · 아래 최종 프롬프트에 반영됩니다</label><Textarea id="system-input" value={r.system} maxLength={1500} onChange={e=>onSystem(e.target.value)} className="system-input"/><div className="vector-caption"><span>{r.prompt.length}자 · 약 {r.tokens} tokens (문자 수÷3, 토크나이저 측정 아님)</span></div><pre className="data-code">{r.prompt}</pre></>;
 return <>{llmText?<><div className="answer-label"><Sparkles size={18}/>Gemini 실제 추론 결과 · 현재 B 입력</div><div className="generated-text llm-result-text">{llmText}</div><div className="diagnostic"><b>모델 입력 근거</b><p>위 답변은 현재 질문과 선택된 {r.selected.length}개 RAG chunk를 사용해 생성되었습니다. 아래 로컬 추출 근거는 검색 결과 확인용입니다.</p></div></>:<><div className="answer-label"><Sparkles size={18}/>로컬 미리보기 · 선택된 근거 문장 추출 (LLM 추론 전)</div>{r.evidence.length?<div className="evidence-list">{r.evidence.map((e,i)=><article key={e.start}><span>{String(i+1).padStart(2,"0")}</span><p>{e.text}<button onClick={()=>onCite(e.id)}>{e.id}<ChevronRight size={13}/></button></p></article>)}</div>:<p className="empty-copy">{r.answer}</p>}<div className="diagnostic"><b>이 결과를 평가하려면</b><p>질문 특징 포함률 {Math.round(r.coverage*100)}% ({r.queryFeatures}개 중 컨텍스트에 포함된 비율). 이것은 정확도·Recall·Faithfulness 점수가 아닙니다. 생성 버튼을 누르면 Gemini 답변으로 바뀝니다.</p></div></>}</>;
}
function Heat({v}:{v:number}){return <span className="heat-value" style={{background:`rgba(81,114,229,${Math.min(v*3,.55)+.03})`}}>{fmt(v)}</span>}
function RankList({rows,r,rerank}:{rows:Result["ranked"];r:Result;rerank:boolean}){
 const positions=useRef(new Map<string,number>()), container=useRef<HTMLDivElement>(null);
 useEffect(()=>{const cards=container.current?.querySelectorAll<HTMLElement>("[data-rank-id]");cards?.forEach(el=>{const id=el.dataset.rankId!;const top=el.getBoundingClientRect().top;const previous=positions.current.get(id);if(previous!==undefined&&previous!==top&&!matchMedia("(prefers-reduced-motion: reduce)").matches)el.animate([{transform:`translateY(${previous-top}px)`},{transform:"translateY(0)"}],{duration:500,easing:"ease-out"});positions.current.set(id,top);});},[rows]);
 return <div className="ranking-list" ref={container}>{rows.length?rows.map((c,i)=><article key={c.id} data-rank-id={c.id} className={r.candidates.some(x=>x.id===c.id)?"candidate":""}><span className="rank-position">{i+1}</span><div><div className="rank-title"><b>{c.id}</b><span>원문 {c.start}–{c.end}</span><em>{rerank?`검색 ${c.rank}위 → ${i+1}위`:i<r.candidates.length?"Top-K 후보":"후보 제외"}</em></div><p>{c.text}</p><div className="ranking-meter"><i style={{width:Math.min(100,(rerank&&r.config.rerank?c.rerankScore:c.score)*100)+"%"}}/></div></div><code>{fmt(rerank&&r.config.rerank?c.rerankScore:c.score)}</code></article>):<p>질문과 공통 특징이 있는 후보가 없습니다.</p>}</div>;
}
export function SnapshotView({label,subtitle,r,baseline}:{label:string;subtitle:string;r:Result;baseline?:Result}){
 const newIds=new Set(baseline?baseline.evidence.map(e=>e.text):[]);
 return <div className={`snapshot snapshot-${label.toLowerCase()}`}><header><span>{label}</span><div><b>{subtitle}</b><small>SIZE {r.config.size} / OVERLAP {r.config.overlap} / K {r.config.topK} / BUDGET {r.config.budget} / RERANK {r.config.rerank?"ON":"OFF"}</small></div></header><p className="snapshot-query">{r.query||"(질문 없음)"}</p><dl><div><dt>청크 수</dt><dd>{r.chunks.length}</dd></div><div><dt>근거 수</dt><dd>{r.selected.length}</dd></div><div><dt>문장 수</dt><dd>{r.evidence.length}</dd></div></dl><div className="source-pills">{r.selected.length?r.selected.map(c=><span key={c.id} title={c.text}>{c.id} <small>{c.start}–{c.end}</small></span>):<span>근거 없음</span>}</div><div className="snapshot-answer">{r.evidence.length?r.evidence.map(e=><p className={baseline&&!newIds.has(e.text)?"new-evidence":""} key={e.start}>{baseline&&!newIds.has(e.text)&&<em>NEW</em>}{e.text}<b>[{e.id}]</b></p>):<p>{r.answer}</p>}</div><details><summary>최종 프롬프트 보기 · {r.prompt.length}자</summary><pre className="data-code">{r.prompt}</pre></details><details><summary>청크 경계·검색 점수·채택 여부 비교</summary><Table><TableHeader><TableRow><TableHead>청크</TableHead><TableHead>범위</TableHead><TableHead>유사도</TableHead><TableHead>채택</TableHead></TableRow></TableHeader><TableBody>{r.ranked.map(c=><TableRow key={c.id}><TableCell>{c.id}</TableCell><TableCell>{c.start}–{c.end}</TableCell><TableCell>{fmt(c.score)}</TableCell><TableCell>{r.selected.some(x=>x.id===c.id)?"✓":"—"}</TableCell></TableRow>)}</TableBody></Table></details></div>;
}
export function Guide({onStart}:{onStart:()=>void}){return <section className="guide panel"><p className="eyebrow">LEARNING GUIDE</p><h2>한 질문으로 RAG의 연결을 이해하는 순서</h2><div className="guide-start"><ol><li>기본 질문과 문서를 유지하고 ‘현재 결과를 A로 고정’을 누릅니다.</li><li>Chunk size만 180 → 60으로 바꿉니다. 청크 경계와 완전한 문장 수를 비교합니다.</li><li>Overlap을 늘려 잘렸던 문맥이 살아나는지 확인합니다.</li><li>Top-K를 1 → 5로 바꾸고, 예산을 200 → 1,200자로 늘립니다.</li><li>재정렬을 켜고 순위·채택 근거가 바뀌는지 봅니다. 변화가 없는 경우도 정상입니다.</li><li>흐름을 재생해 각 노드의 현재 계산 결과를 확인하고, 마지막 근거 추출 결과에서 B 입력 기반 Gemini 답변을 확인합니다.</li></ol><Button onClick={onStart}>이 예제로 실험하기<ArrowRight size={16}/></Button></div><div className="guide-lessons">{steps.map((s,i)=>{const Icon=s.icon;return <article key={s.en}><div><span>{String(i+1).padStart(2,"0")}</span><Icon size={22}/></div><h3>{s.name}</h3><p>{s.description}</p><code>{s.formula}</code><small>{s.pitfall}</small></article>})}</div><h3>실서비스로 넘어갈 때</h3><p>문서 로더 → 구조 보존 청킹 → 신경망 임베딩 → pgvector 같은 저장소 → 검색 → cross-encoder → 컨텍스트 → 실제 LLM으로 교체할 수 있습니다. 운영 단계에서는 버전·적용일 필터, 인용 검증, 평가셋 기반 Recall과 Faithfulness, 비용·지연시간 로그를 추가합니다.</p><p className="muted">검색과 설정 변경은 브라우저에서 계산합니다. 질문·원문·지시문을 편집하고 A를 고정한 다음 B를 변경하세요. 흐름 재생의 마지막 단계나 A/B 생성 버튼을 눌렀을 때만 Google에 전송됩니다. 입력과 A 기준은 현재 브라우저 세션에서 복원되며, 비용 통계와 생성 결과는 서버에 저장됩니다.</p></section>}

