"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
export default function ConnectionPage(){
 const [configured,setConfigured]=useState<boolean|null>(null),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('서버 설정 확인 중…'),[httpStatus,setHttpStatus]=useState<number|null>(null),[checkedAt,setCheckedAt]=useState('');
 function markChecked(){setCheckedAt(new Date().toLocaleTimeString('ko-KR'));}
 async function load(){try{const r=await fetch('/api/connection',{cache:'no-store',signal:AbortSignal.timeout(10000)});const d=await r.json();setConfigured(d.configured===true);setVerified(d.verified===true);setHttpStatus(r.status);setMessage(d.error||(d.verified?'Google 모델 조회 성공 · 이 서버 세션에서 유지 중':d.configured?'키 존재 · 모델 검증 전':'키 미등록'));markChecked();}catch{setConfigured(null);setVerified(false);setHttpStatus(null);setMessage('상태 조회에 실패했습니다. 아래 버튼으로 다시 확인하세요.');}}
 useEffect(()=>{void load();},[]);
 async function verify(){setBusy(true);setVerified(false);setHttpStatus(null);setMessage('1/2 서버 키 존재 여부 확인 중…');try{const r=await fetch('/api/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'verify'}),signal:AbortSignal.timeout(15000)});const d=await r.json();setHttpStatus(r.status);setConfigured(d.configured===true);setVerified(d.verified===true);setMessage(r.ok?'2/2 Google 모델 조회 성공 · 생성은 수행하지 않음':`${d.error||'연결 검증 실패'} (${d.code||'connection_error'}${d.httpStatus?`, HTTP ${d.httpStatus}`:''})`);markChecked();}catch{setHttpStatus(null);setMessage('연결 검증 시간이 초과되었습니다. 서버 상태를 확인하세요.')}finally{setBusy(false)}}
 async function clear(){setBusy(true);try{const r=await fetch('/api/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'clear'}),signal:AbortSignal.timeout(10000)});const d=await r.json();setConfigured(d.configured===true);setVerified(false);setHttpStatus(r.status);setMessage(r.ok?'서버 메모리의 API 키와 검증 상태를 비웠습니다. .env를 변경했다면 서버를 재시작하세요.':d.error||'API 키를 비우지 못했습니다.');markChecked();}catch{setMessage('API 키 삭제 요청에 실패했습니다.')}finally{setBusy(false)}}
 return <><div className="page-title"><div><p>LOCAL ENVIRONMENT</p><h1>모델 연결</h1><span>키는 내 컴퓨터의 서버 프로세스에서만 읽습니다.</span></div></div><div className="connection-layout"><section className="connection-card"><div className="provider-logo">G</div><h2>Google Gemini · 로컬 실행</h2><ol className="setup-steps"><li><span>1</span><div><b>프로젝트 루트에 .env 만들기</b><p>.env.example을 .env로 복사하세요.</p></div></li><li><span>2</span><div><b>환경변수 설정</b><pre>GOOGLE_API_KEY=발급받은_키</pre><p>웹페이지에 키를 입력하거나 업로드하지 않습니다.</p></div></li><li><span>3</span><div><b>서버 재시작</b><p>터미널에서 Ctrl+C 후 npm.cmd run dev를 실행하세요.</p></div></li></ol><p role="status" className={busy?'connection-progress':verified?'connection-success':'connection-result'}>{message}</p><div className="connection-checks"><span className={configured===true?'check-ok':''}>키 존재: {configured===true?'확인':'미확인'}</span><span className={verified?'check-ok':''}>모델 조회: {verified?'성공':'미검증'}</span><span>HTTP: {httpStatus??'대기'}</span>{checkedAt&&<span>확인 시각: {checkedAt}</span>}</div><div className="generation-actions"><Button disabled={busy||configured===false} onClick={verify}>{busy?'Google 모델 조회 중…':'Google 연결 확인 · 추론 없음'}</Button><Button variant="outline" disabled={busy||configured!==true} onClick={clear}>서버 API 키 비우기</Button></div><p className="muted">키 비우기는 현재 서버 프로세스 메모리에서만 삭제합니다. .env 파일과 영구 시스템 환경변수는 변경하지 않습니다.</p><p className="muted">이 버튼은 모델 목록 조회만 합니다. 실제 RAG 답변은 <a href="/compare">A/B 비교·생성</a>에서 생성 버튼을 눌렀을 때만 실행됩니다.</p></section><aside className="connection-aside"><section><h3>설정 변경은 무료</h3><p>청킹, 검색, 예상 비용 계산과 통계 저장은 로컬에서 처리합니다. A/B 화면에서 생성 버튼을 누를 때만 질문과 검색된 근거를 Google로 전송합니다.</p><p>기록: data/rag-explorer.sqlite</p><a href="/compare" className="primary-link">A/B 비교로 이동 →</a></section><section><h3>서버 전용 비밀값</h3><p>GOOGLE_API_KEY에 NEXT_PUBLIC_ 접두사를 붙이지 마세요. 키 원문은 브라우저 응답이나 통계 DB에 저장하지 않습니다.</p></section></aside></div></>;
}
