"use client";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {useLab} from "@/components/workspace";
import {SnapshotView} from "@/components/lab-details";
import {estimateCost,stableInput,type ExperimentInput} from "@/lib/cost";
import type {Generation} from "@/lib/generation";
export default function Compare(){
 const {input,baseline,result,a,update,pin,stats,refresh,auth}=useLab();const [busy,setBusy]=useState(false),[error,setError]=useState(""),[unknownTarget,setUnknownTarget]=useState<string|null>(null),[outputs,setOutputs]=useState<Record<string,{data:Generation&{cached?:boolean};signature:string}>>({});
 function pinCurrentAsBaseline(){if(busy)return;pin();setOutputs({});setError("");setUnknownTarget(null);}
 async function run(){const confirmUnknown=!!unknownTarget;if(busy)return;setBusy(true);setError("");try{for(const [label,snapshot] of [["A",baseline],["B",input]] as [string,ExperimentInput][]){const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...snapshot,...(confirmUnknown?{confirmUnknown:true}:{})}),signal:AbortSignal.timeout(55000)});const data=await response.json() as Generation&{error?:string;code?:string;cached?:boolean};if(!response.ok){if(data.code==="unknown_confirmation_required"){setUnknownTarget(label);setError("이전 요청은 결과가 확인되지 않았습니다. Google 사용 내역을 확인했다면 같은 생성 버튼을 한 번 더 눌러 명시적으로 재시도하세요.");}throw Error(data.error||"생성 실패");}setUnknownTarget(null);setOutputs(v=>({...v,[label]:{data,signature:stableInput(snapshot)}}));}}catch(e){if(!(e instanceof Error&&e.message.includes("이전 요청은")))setError(e instanceof Error?e.message:"응답을 확인하지 못했습니다.");}finally{setBusy(false);void refresh();}}
 return <><div className="page-title"><div><p>COMPARE BEFORE YOU GENERATE</p><h1>A/B 비교와 답변 생성</h1><span>예상 비용을 먼저 보고, 필요할 때만 모델을 실행하세요.</span></div><Button onClick={pinCurrentAsBaseline} disabled={busy}>현재 B를 A로 고정</Button></div><div className="compare-toolbar"><label>Temperature<Input aria-label="Temperature" type="number" min={0} max={1} step={.1} value={input.settings.temperature} onChange={e=>update({settings:{...input.settings,temperature:Math.max(0,Math.min(1,Number(e.target.value)))}})}/></label><label>최대 출력 토큰<Input aria-label="최대 출력 토큰" type="number" min={128} max={1024} step={128} value={input.settings.maxTokens} onChange={e=>update({settings:{...input.settings, maxTokens:Math.max(128,Math.min(1024,Math.round(Number(e.target.value)||128)))}})}/></label><div><small>설정은 B에 적용 · A는 고정된 상태</small><Button onClick={run} disabled={busy||auth!==true||!stats?.configured}>{busy?"생성 중…":"A/B 답변 생성 · 최대 2회 호출"}</Button>{!stats?.configured&&<a href="/connection">모델 연결을 먼저 완료하세요 →</a>}</div></div>
 <div className="comparison-budget">{[["A",a,baseline],["B",result,input]].map(([label,r,s])=>{const est=estimateCost(r as typeof result,(s as ExperimentInput).settings);return <article key={label as string}><span>{label as string} · 생성 예상 예산</span><strong>${est.totalUsd.toFixed(6)}</strong><small>입력 약 {est.inputTokens} / 출력 한도 {est.outputLimit} 토큰</small></article>})}<p>문자 기반 추정치입니다. 설정 변경은 $0이며, 저장된 동일 답변을 재사용하면 추가 호출이 없습니다.</p></div>
 <Tabs defaultValue="evidence"><TabsList><TabsTrigger value="evidence">검색 근거 비교</TabsTrigger><TabsTrigger value="answers">LLM 답변</TabsTrigger><TabsTrigger value="system">시스템 지시문</TabsTrigger></TabsList><TabsContent value="evidence"><div className="comparison-grid"><SnapshotView label="A" subtitle="고정된 기준" r={a}/><SnapshotView label="B" subtitle="현재 실험" r={result} baseline={a}/></div></TabsContent><TabsContent value="answers">{error&&<p className="error-box" role="alert">{error}</p>}<div className="comparison-grid">{["A","B"].map(label=><article className="answer-panel" key={label}><h2>{label} · 생성 답변</h2>{outputs[label]?<><p className="status-copy">{outputs[label].signature!==stableInput(label==="A"?baseline:input)?"입력 변경됨 · 이전 결과":outputs[label].data.cached?"저장 답변 재사용 · 추가 비용 $0":"새로 생성한 답변"}</p><p className="generated-text">{outputs[label].data.text}</p><small>입력 {outputs[label].data.inputTokens??"미확인"} / 출력 {outputs[label].data.outputTokens??"미확인"} 토큰 · 원 실행 환산 비용 {outputs[label].data.estimatedUsd===null?"미확인":`$${outputs[label].data.estimatedUsd!.toFixed(6)}`}</small></>:<p>아직 생성하지 않았습니다. 위 실행 버튼을 누르면 답변이 표시됩니다.</p>}</article>)}</div></TabsContent><TabsContent value="system"><div className="answer-panel"><label htmlFor="system-compare">B의 SYSTEM 지시문</label><Textarea id="system-compare" value={input.system} maxLength={1500} onChange={e=>update({system:e.target.value})}/><p>이 지시문은 다음 생성 요청에 반영됩니다. 질문·근거가 같아도 답변 형식이 바뀔 수 있습니다.</p></div></TabsContent></Tabs>{error&&<p className="error-box" role="alert">{error}</p>}</>;
}
